title: Ping Chang
logo: /assets/img/profile_picture.JPG
description: >
  About Me:<br><br>
  Hello! I am Ping Chang, a recent graduate from NYU Tandon School of Engineering with a Master of Science in Computer Science, where I maintained a GPA of 3.7 and earned the Tandon Onwards Scholarship.<br><br>
  I am passionate about data engineering and analysis, with expertise in big data technologies such as PySpark, Hadoop MapReduce, MongoDB, and MySQL. Proficient in Python, I have developed web applications, predictive models, and interactive visualizations.<br><br>
  Currently, I seek a position as a Data Engineer or Data Analyst to apply my technical skills and analytical abilities. <br><br>
  LinkedIn: <a href="https://www.linkedin.com/in/pingchang-923/" target="_blank">pingchang-923</a> <br>
  GitHub: <a href="https://github.com/PingChang1999/" target="_blank">PingChang1999</a> <br>
  YouTube: <a href="https://www.youtube.com/@SnownaVG/" target="_blank">SnownaVG</a> <br>
show_downloads: true
theme: jekyll-theme-minimal
