title: Ping Chang
logo: /assets/img/profile_picture.JPG
description: >
  About Me:<br>
  Hello! I am Ping Chang, a recent graduate from NYU Tandon School of Engineering with a Master of Science in Computer Science, where I maintained a GPA of 3.7 and earned the Tandon Onwards Scholarship.<br><br>
  I am passionate about data engineering and analysis, with expertise in big data technologies such as PySpark, Hadoop MapReduce, MongoDB, and MySQL. Proficient in Python, I have developed web applications, predictive models, and interactive visualizations.<br>
  My links: <a href="https://www.linkedin.com/in/pingchang-923/" target="_blank">LinkedIn</a>
show_downloads: true
theme: jekyll-theme-minimal
