title: Ping Chang
logo: /assets/img/profile_picture.JPG
description: >
  About Me:<br><br>
  Hello! I am Ping Chang, a recent graduate from NYU Tandon School of Engineering with a Master of Science in Computer Science, where I maintained a GPA of 3.7 and earned the Tandon Onwards Scholarship.<br><br>
  I am passionate about data engineering and analysis, with expertise in big data technologies such as PySpark, Hadoop MapReduce, MongoDB, and MySQL. Proficient in Python, I have developed web applications, predictive models, and interactive visualizations.<br><br>
  Currently, I seek a position as a Data Engineer or Data Analyst to apply my technical skills and analytical abilities. <br><br>
  Beyond my professional work, I have a deep passion for baseball statistics, inspired by my upbringing in Taiwan and watching Chien-Ming Wang. This passion drives my personal projects, blending my love for baseball with my technical expertise.<br><br>
  LinkedIn: <a href="https://www.linkedin.com/in/pingchang-923/" target="_blank">pingchang-923</a>
show_downloads: true
theme: jekyll-theme-minimal
