title: Ping Chang
logo: /assets/img/profile_picture.JPG
description: >
  Hello! <br>
  My links: <a href="https://www.linkedin.com/in/pingchang-923/" target="_blank">LinkedIn</a>
show_downloads: true
theme: jekyll-theme-minimal
