title: Ping Chang
logo: /assets/img/profile_picture.JPG
description: >
  About Me:<br><br>
  Hello! I am Ping Chang, a recent graduate from NYU Tandon School of Engineering with a Master of Science in Computer Science, where I maintained a GPA of 3.7 and earned the Tandon Onwards Scholarship.<br><br>
  Currently, I seek a position as a Data Engineer or Data Analyst to apply my technical skills and analytical abilities. <br><br>
  LinkedIn: <a href="https://www.linkedin.com/in/pingchang-923/" target="_blank">pingchang-923</a> <br>
  GitHub: <a href="https://github.com/PingChang1999/" target="_blank">PingChang1999</a> <br>
  Facebook: <a href="https://www.facebook.com/pingchang990923" target="_blank">Ping Chang</a> <br>
show_downloads: true
theme: jekyll-theme-minimal
